### ISSUE TITLE
Cannot change configuration

### ISSUE THREAD

**Issue by tymmej** [HanSolo/digital5#8]
I have a problem with configuration.
It works only once after installation. After I click save it updates on watch and I can't change settings anymore.

I get:
translation: "An error occured during downloading settings from device. Try again?"
original text (polish): "wystąpił błąd podczas pobierania ustawień z urządzenia. Spróbować ponownie?"

I'm using iOS with newest Garmin app, I haven't problems with other watch faces. I can change their settings without problems.

Anyway, great watch face!

Device: Garmin Fenix 5, FW: 5.40

PS I tried sending mail through Garmin Connect IQ - contact with developer, but I get no feedback from webpage - I'm not sure it sent mail so I'm writing here.

**Comment by HanSolo** [comment]
Hmm...strange, works fine on my fenix 5x with 5.40 and in the emulator too. Can you try to reinstall it? It would be great if I could reproduce it to be able to fix it. Thank's for the report, very appreciated.
Cheers, Gerrit

**Comment by tymmej** [comment]
That's how I change settings: delete, one chance to change settings, doesn't work again.

**Comment by HanSolo** [comment]
Darn, tried different things but can't reproduce. Did you accept all requirements? Sorry for the inconvenience, will try to find the problem.

**Comment by tymmej** [comment]
Which requirements?
As far as I know there's only information during installation.

[This](https://apps.garmin.com/pl-PL/apps/abc0fde3-23d3-4c8d-92ec-a2fd14aeab2f) watchface need same permission and works.

**Comment by tymmej** [comment]
1) I go to watchfaces in Garmin App
2) select SC 8 watch face
3) click settings
4) change something
5) save
6) select Digital 5
7) click settings
8) An error occured during downloading settings from device

The effect is the same wheter watchface is currently selected on watch or not.

**Comment by HanSolo** [comment]
Ok, did exactly the same on my watch but it always works, no matter what I try. Will try to figure out the error message you get, maybe I'll find a hint there.

**Comment by RHNeM** [comment]
My problem is shown in the video (Fenix 5, FW: 5.40, I tried reinstall, it did not help) https://youtu.be/NCR_XoWZgls

**Comment by HanSolo** [comment]
Thank's a lot will try to figure out the problem

**Comment by HanSolo** [comment]
So I saw that you use an Android phone which I never tested. Will install it on my Sony Z3 compact and check if I can reproduce your issue there. I personally use an iPhone where I don't see that issue.

**Comment by HanSolo** [comment]
Ok, I see the problem when using the Garmin Android app. So if I use the Garmin iPhone app it works fine but with the Android app I also see the behavior that the field content is missing.
I'll try figure out why it works on iOS but not on Android and will let you know

**Comment by HanSolo** [comment]
So I've spent some time to figure out the problem but can't find something because I can only reproduce it using and Android phone but not in the simulator :(
I've also searched in the Connect IQ store for other watchfaces and found a couple that have similar problems with the Android Connect App.
You could try to adjust the settings using the Garmin Express app which should work too.

**Comment by RHNeM** [comment]
Thank you. You are right, I tried other watchfaces and found the same problem with the other one. This was also fine until recently. The problem is obviously the last firmware of Fenix 5. I'm sorry about the last critical review.
What can be changed in Garmin Express to change functionality watchface?

**Comment by HanSolo** [comment]
No worries, you found the problem and you cannot work with it...so it is absolutetly correct to vote it down :)
As far as I remember you adjust the settings of the watchface also within the Garmin Express application. Therefor you have to connect the watch with the usb cable to your computer, start Garmin Express and when it is connected you should be able to modify the settings of all installed app like in the mobile application.

**Comment by RHNeM** [comment]
Thank you. Setting up via Garmin Express works flawlessly.

**Comment by HanSolo** [comment]
Ha...good to know...thx for your help.

**Comment by HanSolo** [comment]
I might have found a solution for your problem. It looks like the Garmin Connect app sends floats instead of integers to the watch. The dropdown boxes for the datafields using integers, meaning to say if you select the first entry from a listbox the Android app will send a 0.0 i stead of a 0 to the watch face. The switch/case block won't work with floats and so you do not see any entries in the datafields. I'm pretty sure I can fix this by casting all values to number (integer) before the switch case block.
Problem is I need to create an official release to be able to test it on my watch with an Android phone but I think it will be worth a try :)
Stay tuned...

**Comment by tymmej** [comment]
For me it works :D

**Comment by HanSolo** [comment]
So you mean with the latest version (1.4.2) ?

**Comment by tymmej** [comment]
Yes

**Comment by HanSolo** [comment]
Awesome...thanks for your patience and for testing :)

**Comment by RHNeM** [comment]
I confirm that the latest version works on android without any problems. Great, thank you.
